# Generated by Django 5.1.7 on 2025-03-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forecast",
            unique_together={("city", "date")},
        ),
    ]
