# Generated by Django 5.1.7 on 2025-03-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0002_alter_forecast_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
