# Generated by Django 5.1.7 on 2025-03-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0003_alter_forecast_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cityName", models.CharField(max_length=100)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
            ],
            options={
                "unique_together": {("latitude", "longitude")},
            },
        ),
    ]
