# Generated by Django 5.1.7 on 2025-03-25 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0004_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecast",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="forecast.city",
            ),
        ),
    ]
