# Generated by Django 5.1.7 on 2025-03-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0005_alter_forecast_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="cloud_cover",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="precipitation",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forecast",
            name="wind_direction",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forecast",
            name="wind_gusts",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forecast",
            name="wind_speed",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
