# Generated by Django 5.1.7 on 2025-03-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0006_forecast_cloud_cover_forecast_precipitation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="coast",
            field=models.BooleanField(default=False),
        ),
    ]
