# Generated by Django 5.1.7 on 2025-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0007_city_coast"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="sswell_direction",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="sswell_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="sswell_period",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="swell_direction",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="swell_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="swell_period",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="tide_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wave",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wave_direction",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wave_period",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wwave_direction",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wwave_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="forecast",
            name="wwave_period",
            field=models.FloatField(null=True),
        ),
    ]
