# Generated by Django 5.1.7 on 2025-03-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0008_forecast_sswell_direction_forecast_sswell_height_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="forecast",
            old_name="sswell_direction",
            new_name="swell2_direction",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="sswell_height",
            new_name="swell2_height",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="sswell_period",
            new_name="swell2_period",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="tide_height",
            new_name="wave_height",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="wave",
            new_name="wind_direction2",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="wwave_direction",
            new_name="wind_speed2",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="wwave_height",
            new_name="wind_wave_direction",
        ),
        migrations.RenameField(
            model_name="forecast",
            old_name="wwave_period",
            new_name="wind_wave_height",
        ),
        migrations.AddField(
            model_name="forecast",
            name="wind_wave_period",
            field=models.FloatField(null=True),
        ),
    ]
